apiVersion: apps/v1
kind: Deployment
metadata:
  name: webkube-deployment
  labels:
    app: webkube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webkube
  template:
    metadata:
      labels:
        app: webkube
    spec:
      containers:
      - name: webkube
        image: mohdatpi/redditclone
        ports:
        - containerPort: 3000
