apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: webkube-service
spec:
  selector:
    # Selector for Pods
    app: webkube
  ports:
    # Port Map
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
